#!/usr/bin/env bash
# this script create a backup file of SQL databases and tar.gz them
DATE=$(date +%d-%m-%Y)
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$DATE.tar.gz" backup.sql
