#!/usr/bin/env bash
# This script its tha task 100, why you no love me?
pgrep -f "100-process_and_pid_file" >> /var/run/holbertonscript.pid
trap "echo Y U no love me?" 2
trap "echo I hate the kill command; rm -r /var/run/holbertonscript.pid; exit" 15 3
while true
do
	echo "To infinity and beyond"
	sleep 2
done