#!/usr/bin/env bash
#this function print and display fizzbuzz

i=1
while [ $i -le 100 ]
do
	if [ $((i%3)) = 0 -a $((i%5)) = 0 ]
	then
	    echo "FizzBuzz"
	elif [ $((i%3)) = 0 ]
	then
	    echo "Fizz"
	elif [ $((i%5)) = 0 ]
	then
	    echo "Buzz"
	else
	    echo "$i"
	fi
	let i+=1
done
